// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tapfhqqgztkeoyeerkpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcGZocXFnenRrZW95ZWVya3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODczNDQsImV4cCI6MjA3MjA2MzM0NH0.8dXjsJ0_TKB6tSYAl1Wlp-z6F1HOR4SYbEDpdE2gX7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});